name: rep
named: {}
views:
  uesio/tests.customhome: true
  uesio/tests.customlogin: true
collections:
  uesio/core.user:
    read: true
    create: false
    edit: false
    delete: false
    modifyall: false
    viewall: false
    fields: {}
  uesio/core.userfile:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/tests.account:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/tests.animal:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/tests.contact:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/tests.tool:
    read: false
    create: false
    edit: false
    delete: false
    modifyall: true
    viewall: false
    fields: {}
routes:
  uesio/tests.customhome: true
  uesio/tests.customlogin: true
files: {}
bots: {}
integrationActions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: false
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
