version: "3.2"
services:
  app:
    build:
      context: "."
      dockerfile: ./apps/platform/Dockerfile
      args:
        # Increment this number to force static asset versions to be refetched when running in Docker
        - GITSHA=latest11
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      UESIO_BUNDLES_BUCKET_NAME: uesiobundlestore-dev
      UESIO_CACHE_SITE_BUNDLES: "true"
      UESIO_DB_DATABASE: postgresio
      UESIO_DB_HOST: host.docker.internal
      UESIO_DB_USER: postgres
      UESIO_DB_PASSWORD: mysecretpassword
      UESIO_DB_PORT: 5432
      UESIO_PLATFORM_AUTHSOURCE_TYPE: cognito
      UESIO_PLATFORM_AUTHSOURCE_CREDENTIALS: uesio/core.cognito
      UESIO_PLATFORM_BUNDLESTORE_CREDENTIALS: uesio/core.aws
      UESIO_PLATFORM_BUNDLESTORE_TYPE: uesio.local
      UESIO_PLATFORM_FILESOURCE_CREDENTIALS: uesio/core.aws
      UESIO_PLATFORM_FILESOURCE_TYPE: uesio.local
      UESIO_SESSION_STORE: redis
      UESIO_USERFILES_BUCKET_NAME: uesiofiles-dev
      UESIO_MOCK_AUTH: "true"
      UESIO_USE_HTTPS: "true"
      PORT: 3000
    volumes:
      - ./apps/platform/ssl:/ssl
