services:
  app:
    build:
      context: "."
      dockerfile: ./apps/platform/Dockerfile
      args:
        # Intentionally leaving BUILD_VERSION blank so that current time is used to ensure static assets are always refetched
        - BUILD_VERSION=
    ports:
      - "${UESIO_PORT:-3000}:${UESIO_PORT:-3000}"
    env_file:
      # Ensures that all UESIO_ environment variables present in the environment are available to the container
      - .env.template
    environment:
      # Due to .env.template, all environment variables that are present in the environment will be passed through to the
      # container.  The below are simply here for convenience to provide defaults for all required variables and variables
      # that are docker related. The below defaults will only be used if the variable in the environment is not set or is
      # empty.  For all other environment variables not listed, they will be passed through to the container as they exist
      # in the environment.
      UESIO_REDIS_HOST: "${UESIO_REDIS_HOST:-redis}"
      UESIO_DB_HOST: "${UESIO_DB_HOST:-db}"
      UESIO_DB_USER: "${UESIO_DB_USER:-postgres}"
      UESIO_DB_PASSWORD: "${UESIO_DB_PASSWORD:-mysecretpassword}"
      UESIO_DB_DATABASE: "${UESIO_DB_DATABASE:-postgresio}"
      UESIO_MOCK_AUTH: "${UESIO_MOCK_AUTH:-true}"
      UESIO_DEV: "${UESIO_DEV:-true}"
      UESIO_DEBUG_SQL: "${UESIO_DEBUG_SQL:-true}"
      UESIO_SESSION_STORE: "${UESIO_SESSION_STORE:-redis}"
      UESIO_PLATFORM_CACHE: "${UESIO_PLATFORM_CACHE:-redis}"
      UESIO_USAGE_HANDLER: "${UESIO_USAGE_HANDLER:-redis}"
    volumes:
      - ./apps/platform/ssl:/ssl
