name: "uesio-test"

services:
  redis:
    image: "redis:alpine"
  db:
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pgtest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 4
      start_period: 10s
  app:
    image: "${APP_IMAGE:?error}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "${UESIO_PORT:-3000}:${UESIO_PORT:-3000}"
    environment:
      UESIO_REDIS_HOST: redis
      UESIO_REDIS_PORT: 6379
      UESIO_BUNDLES_BUCKET_NAME: uesiobundlestore-dev
      UESIO_CACHE_SITE_BUNDLES: "true"
      UESIO_DB_DATABASE: pgtest
      UESIO_DB_HOST: db
      UESIO_DB_USER: postgres
      UESIO_DB_PASSWORD: postgres
      UESIO_DB_PORT: 5432
      UESIO_PLATFORM_BUNDLESTORE_CREDENTIALS: uesio/core.aws
      UESIO_PLATFORM_BUNDLESTORE_TYPE: uesio.local
      UESIO_PLATFORM_FILESOURCE_CREDENTIALS: uesio/core.aws
      UESIO_PLATFORM_FILESOURCE_TYPE: uesio.local
      UESIO_SESSION_STORE: redis
      UESIO_USERFILES_BUCKET_NAME: uesiofiles-dev
      UESIO_MOCK_AUTH: "${UESIO_MOCK_AUTH:-true}"
      # TODO: should default to false (localhost refactor)
      UESIO_USE_HTTPS: "${UESIO_USE_HTTPS:-true}"
      UESIO_ALLOW_INSECURE_COOKIES: "${UESIO_ALLOW_INSECURE_COOKIES:-false}"
      UESIO_DEBUG_SQL: "${UESIO_DEBUG_SQL:-true}"
      UESIO_PORT: "${PORT:-3000}"
      UESIO_HOST: "${HOST-}"
      UESIO_DEV: ${UESIO_DEV:-true}
      # TODO: should default to localhost (localhost refactor)
      UESIO_PRIMARY_DOMAIN: "${UESIO_PRIMARY_DOMAIN:-uesio-dev.com}"
      UESIO_LOG_LEVEL: "${UESIO_LOG_LEVEL--4}"
    volumes:
      - ./apps/platform/ssl:/ssl
    command: sh -c "./uesio migrate && ./uesio seed && ./uesio serve"
