name: "uesio-test"

services:
  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 4
      start_period: 10s
  db:
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pgtest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 4
      start_period: 10s
  app:
    image: "${APP_IMAGE:?APP_IMAGE is required}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", 'wget -q --no-check-certificate $(if [ "$${UESIO_USE_HTTPS}" = "true" ]; then echo "https"; else echo "http"; fi)://studio.$${UESIO_PRIMARY_DOMAIN}:$${UESIO_PORT}/health']
      interval: 5s
      timeout: 10s
      retries: 4
      start_period: 10s
    ports:
      - "${UESIO_PORT:-3000}:${UESIO_PORT:-3000}"
    environment:
      UESIO_REDIS_HOST: redis
      UESIO_DB_HOST: db
      UESIO_DB_USER: postgres
      UESIO_DB_PASSWORD: postgres
      UESIO_DB_DATABASE: pgtest
      UESIO_MOCK_AUTH: true
      UESIO_DEBUG_SQL: true
      UESIO_DEV: true
      UESIO_SESSION_STORE: redis
      UESIO_PLATFORM_CACHE: redis
      UESIO_USAGE_HANDLER: redis
      # All the above are fixed configuration for tests and we do not
      # pass through any other environment values that may be set
      # to ensure a controlled test environment.  The below will
      # honor current environment variables to support running
      # in CI and local dev to ensure we respect specific machine
      # setup (e.g., ssl installed, hosts entries, etc.)
      UESIO_USE_HTTPS: "${UESIO_USE_HTTPS:-false}"
      UESIO_PORT: "${UESIO_PORT:-3000}"
      UESIO_PRIMARY_DOMAIN: "${UESIO_PRIMARY_DOMAIN:-localhost}"
      UESIO_LOG_LEVEL: "${UESIO_LOG_LEVEL:-0}"
      # for situations where UESIO_PRIMARY_DOMAIN is not localhost and
      # UESIO_USE_HTTPS is not true, we need to pass this through
      UESIO_ALLOW_INSECURE_COOKIES: "${UESIO_ALLOW_INSECURE_COOKIES:-false}"
    volumes:
      - ./apps/platform/ssl:/ssl
    command: sh -c "cat /etc/hosts && ping -w 15 studio.localhost && cp /ssl/certificate.crt /usr/local/share/ca-certificates && update-ca-certificates && ./uesio migrate && ./uesio seed && ./uesio serve"
