services:
  app:
    build:
      context: "."
      dockerfile: ./apps/platform/Dockerfile
      args:
        # Intentionally leaving BUILD_VERSION blank so that current time is used to ensure static assets are always refetched
        - BUILD_VERSION=
    ports:
      # TODO: PORT variable should change to have UESIO prefix
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      # TODO: REDIS_HOST variable should change to have UESIO prefix
      REDIS_HOST: host.docker.internal
      # TODO: REDIS_PORT variable should change to have UESIO prefix
      REDIS_PORT: 6379
      UESIO_BUNDLES_BUCKET_NAME: uesiobundlestore-dev
      UESIO_CACHE_SITE_BUNDLES: "true"
      UESIO_DB_DATABASE: postgresio
      UESIO_DB_HOST: host.docker.internal
      UESIO_DB_USER: postgres
      UESIO_DB_PASSWORD: mysecretpassword
      UESIO_DB_PORT: 5432
      UESIO_PLATFORM_BUNDLESTORE_CREDENTIALS: uesio/core.aws
      UESIO_PLATFORM_BUNDLESTORE_TYPE: uesio.local
      UESIO_PLATFORM_FILESOURCE_CREDENTIALS: uesio/core.aws
      UESIO_PLATFORM_FILESOURCE_TYPE: uesio.local
      UESIO_SESSION_STORE: redis
      UESIO_USERFILES_BUCKET_NAME: uesiofiles-dev
      UESIO_MOCK_AUTH: "${UESIO_MOCK_AUTH:-true}"
      UESIO_USE_HTTPS: "${UESIO_USE_HTTPS:-true}"
      UESIO_ALLOW_INSECURE_COOKIES: "${UESIO_ALLOW_INSECURE_COOKIES:-false}"
      UESIO_DEBUG_SQL: "${UESIO_DEBUG_SQL:-true}"
      # TODO: PORT variable should change to have UESIO prefix
      PORT: "${PORT:-3000}"
      # TODO: HOST variable should change to have UESIO prefix
      HOST: "${HOST-}"
      UESIO_DEV: ${UESIO_DEV:-true}
      UESIO_PRIMARY_DOMAIN: "${UESIO_PRIMARY_DOMAIN:-uesio-dev.com}"
      # TODO: LOG_LEVEL variable should change to have UESIO prefix
      LOG_LEVEL: "${LOG_LEVEL--4}"
    volumes:
      - ./apps/platform/ssl:/ssl
