root = "."
testdata_dir = "testdata"
tmp_dir = ".watch"

[build]
  args_bin = []
  bin = "./.watch/main"
  cmd = "go build -o ./.watch/main ."
  delay = 1000
  exclude_dir = ["localbundlestore", "migrations", "migrations_test", "scripts", "seed", "ssl", "userfiles", "uesio-bundles", "uesio-userfiles"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "gohtml"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 3000
  enabled = false
  proxy_port = 8000

[screen]
  clear_on_rebuild = false
  keep_scroll = true
