import { component } from "@uesio/ui";
import alert from "../components/alert/alert";
import avatar from "../components/avatar/avatar";
import breadcrumbs from "../components/breadcrumbs/breadcrumbs";
import buttonset from "../components/buttonset/buttonset";
import button from "../components/button/button";
import card from "../components/card/card";
import column from "../components/column/column";
import container from "../components/container/container";
import deck from "../components/deck/deck";
import field from "../components/field/field";
import grid from "../components/grid/grid";
import griditem from "../components/griditem/griditem";
import image from "../components/image/image";
import icon from "../components/icon/icon";
import table from "../components/table/table";
import typography from "../components/typography/typography";
import selectfield from "../components/selectfield/selectfield";
import checkboxfield from "../components/checkboxfield/checkboxfield";
import textfield from "../components/textfield/textfield";
import autocompletefield from "../components/autocompletefield/autocompletefield";
import imageupload from "../components/imageupload/imageupload";
import fileupload from "../components/fileupload/fileupload";
import dialog from "../components/dialog/dialog";
import file from "../components/file/file";
component.registry.register("material", "alert", alert);
component.registry.register("material", "avatar", avatar);
component.registry.register("material", "breadcrumbs", breadcrumbs);
component.registry.register("material", "buttonset", buttonset);
component.registry.register("material", "button", button);
component.registry.register("material", "card", card);
component.registry.register("material", "column", column);
component.registry.register("material", "container", container);
component.registry.register("material", "deck", deck);
component.registry.register("material", "field", field);
component.registry.register("material", "grid", grid);
component.registry.register("material", "griditem", griditem);
component.registry.register("material", "image", image);
component.registry.register("material", "icon", icon);
component.registry.register("material", "table", table);
component.registry.register("material", "typography", typography);
component.registry.register("material", "selectfield", selectfield);
component.registry.register("material", "checkboxfield", checkboxfield);
component.registry.register("material", "textfield", textfield);
component.registry.register("material", "autocompletefield", autocompletefield);
component.registry.register("material", "imageupload", imageupload);
component.registry.register("material", "fileupload", fileupload);
component.registry.register("material", "dialog", dialog);
component.registry.register("material", "file", file);