name: Non-master branch build
on:
  push:
    branches-ignore:
      - "master"
    tags-ignore:
      - "*"
    secrets:
      AWS_ACCESS_KEY_STATIC_ASSETS:
        required: true
      AWS_SECRET_ACCESS_KEY_STATIC_ASSETS:
        required: true
      AWS_STATIC_ASSETS_BUCKET:
        required: true
      AWS_REGION:
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      FULL_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Uesio CLI Symlink
        shell: bash
        run: |
          # Symlink for Uesio CLI, which is created in build and then used in subsequent builds and tests
          mkdir -p dist/cli
          sudo ln -s $PWD/dist/cli/uesio /usr/local/bin/uesio
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: "npm"
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache-dependency-path: apps/*/go.sum
      - name: Install, lint, build, test
        shell: bash
        run: |
          npm ci
          npm run prettier-check
          npm run affected:lint -- --base=origin/master --head=$GITHUB_SHA --parallel
          npm run build-all
          npm run affected:test -- --base=origin/master --head=$GITHUB_SHA --parallel
          export GITSHA=$(echo ${GITHUB_SHA} | cut -c1-8)
          echo "GITSHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - uses: Noelware/s3-action@691f113810fbb2c987cd89664f769e8a32a6edea
        name: Upload vendor files to S3
        id: s3UploadVendor
        with:
          directories: |
            ./dist/vendor
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_STATIC_ASSETS }}
          bucket: ${{ secrets.AWS_STATIC_ASSETS_BUCKET }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STATIC_ASSETS}}
          prefix: /static/vendor
          region: ${{ secrets.AWS_REGION }}
          object-acl: ""
      - uses: Noelware/s3-action@691f113810fbb2c987cd89664f769e8a32a6edea
        name: Upload Uesio static files to S3
        id: s3UploadUesio
        with:
          directories: |
            ./dist/ui
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_STATIC_ASSETS }}
          bucket: ${{ secrets.AWS_STATIC_ASSETS_BUCKET }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STATIC_ASSETS}}
          prefix: "/$GITSHA/static/ui"
          region: ${{ secrets.AWS_REGION }}
          object-acl: ""
