name: Non-master branch build
on:
    push:
        branches-ignore:
            - master
            - workflow-changes
jobs:
    build-and-test:
        uses: https://github.com/TheCloudMasters/uesio/.github/workflows/build.yml@workflow-changes
