name: Uesio CLI Release

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Release tag"
        required: true
        default: "v0-0-1"
        type: string
      releaseNotes:
        description: "Release notes"
        required: true
        default: "# Bug fixes\n - Fix One\n\n# Features\n - Feature one"
        type: string

jobs:
  validate:
    name: Validate inputs
    runs-on: ubuntu-latest
    steps:
      - name: Validate workflow inputs
        shell: bash
        env:
          releaseTag: ${{ inputs.releaseTag }}
        run: |
          pattern="^v[0-9]{1,3}-[0-9]{1,3}-[0-9]{1,3}$"
          if [[ ! $releaseTag =~ $pattern ]]; then
            echo "Invalid release tag: $releaseTag"
            exit 1
          fi
  publish:
    name: Build asset for ${{ matrix.goos }} - ${{ matrix.goarch }}
    runs-on: ${{ matrix.os }}
    needs:
      - validate
    env:
      releaseTag: ${{ inputs.releaseTag }}
      releaseNotes: ${{ inputs.releaseNotes }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            artifact_name: uesio
            asset_name: uesio-linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            artifact_name: uesio
            asset_name: uesio-linux-arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
            artifact_name: uesio.exe
            asset_name: uesio-windows-amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            artifact_name: uesio
            asset_name: uesio-macos-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            artifact_name: uesio
            asset_name: uesio-macos-arm64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3
          cache-dependency-path: apps/*/go.sum
      - name: Build CLI
        shell: bash
        env:
          outputPath: "dist/${{ matrix.asset_name }}/${{ matrix.artifact_name }}"
        run: |
          cd apps/cli
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $outputPath
          cd ../..
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: apps/cli/dist/${{ matrix.asset_name }}/${{ matrix.artifact_name }}
          asset_name: "${{ matrix.asset_name }}-${{ env.releaseTag }}"
          tag: ${{ env.releaseTag }}
          overwrite: true
          release_name: "Uesio CLI: ${{ env.releaseTag }}"
          body: ${{ env.releaseNotes }}
