name: Uesio CLI Release

on:
  push:
    tags:
      - "release-cli-v[0-9]{1,2}-[0-9]{1,3}-[0-9]{1,3}"

jobs:
  publish:
    name: Build asset for ${{ matrix.goos }} - ${{ matrix.goarch }}
    runs-on: ${{ matrix.os }}
    env:
      releaseName: ${${{ github.ref }}//release-cli-/}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            artifact_name: uesio
            asset_name: uesio-linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            artifact_name: uesio
            asset_name: uesio-linux-arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
            artifact_name: uesio.exe
            asset_name: uesio-windows-amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            artifact_name: uesio
            asset_name: uesio-macos-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            artifact_name: uesio
            asset_name: uesio-macos-arm64
    steps:
      - name: Test
        shell: bash
        run: echo "release name is $releaseName"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache-dependency-path: apps/*/go.sum
      - name: Build CLI
        shell: bash
        run: |
          cd apps/cli
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ matrix.asset_name }}/${{ matrix.artifact_name }}
          cd ../..
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: apps/cli/dist/${{ matrix.asset_name }}/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref_name }}
          overwrite: true
          release_name: $releaseName
          body: "Uesio CLI Release $releaseName"
