name: Build and Deploy DEV

on:
    push:
        branches:
            - workflow-changes

env:

jobs:
    build-and-test:
        uses: ./.github/workflows/build.yml
    deploy:
        name: Deploy to DEV
        runs-on: ubuntu-latest
        environment: dev
        needs: build-and-test

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
