name: Master/Release Branch Build
on:
  push:
    branches:
      - master
      - workflow-changes
      # - stable-december-2022
    secrets:
      GH_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        go-version: [~1.19]
    outputs:
      newImage: ${{ steps.dockerize.outputs.fullImage }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - name: Use Go ${{ matrix.go-version }}
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: ${{ matrix.go-version }}
      #   id: go
      # - name: Cache ~/.npm
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-${{ matrix.node-version }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-${{ matrix.node-version }}-node-
      # - name: Install npm Dependencies
      #   run: npm ci
      # - name: Cache ./node_modules/.cache for nx usage
      #   uses: actions/cache@v2
      #   with:
      #     path: ./node_modules/.cache
      #     key: ${{ runner.os }}-${{ matrix.node-version }}-node-cache-${{ hashFiles('./*.json') }}-${{ github.ref }}
      #     restore-keys: |
      #       ${{ runner.os }}-${{ matrix.node-version }}-node-cache-${{ hashFiles('./*.json') }}
      #       ${{ runner.os }}-${{ matrix.node-version }}-node-cache-
      # - name: Cache Go modules
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-
      # - name: Lint
      #   shell: bash
      #   run: |
      #     npm run prettier-check
      #     npm run affected:lint -- --base=origin/master --head=$GITHUB_SHA --parallel

      # - name: Build All
      #   shell: bash
      #   run: |
      #     npm run build-all

      # - name: Test
      #   shell: bash
      #   run: |
      #     npm run affected:test -- --base=origin/master --head=$GITHUB_SHA --parallel
      #     npm run affected:e2e -- --base=origin/master --head=$GITHUB_SHA --parallel
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2
      - name: Compute short sha
        id: shortsha
        env:
          FULL_SHA: ${{ github.sha }}
        run: echo "GITSHA=`echo ${FULL_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Docker Build, Tag, and Push to ECR
        id: dockerize
        env:
          IMAGE_TAG: ${{ steps.login-ecr.outputs.registry }}/uesio:${{ github.sha }}
          FULL_SHA: ${{ github.sha }}
          # docker build -t $IMAGE_TAG --build-arg git_sha=${GITSHA} -f ./apps/platform/Dockerfile .
          # docker push $IMAGE_TAG
        run: |
          echo "FULL_SHA is $FULL_SHA"
          echo "GITSHA is $GITSHA"
          echo "IMAGE_TAG is $IMAGE_TAG"
          echo "fullImage=${IMAGE_TAG}" >> $GITHUB_OUTPUT
      - name: Check vars
        run: echo "${{ steps.dockerize.outputs.fullImage }}"

  update-dev-branch:
    if: github.ref_name == 'workflow-changes'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: thecloudmasters/uesio-infra
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: Update Docker container image tag for dev
        env:
          NEW_IMAGE: ${{ needs.build.outputs.newImage }}
        run: |
          echo "Docker image SHA updated to $NEW_IMAGE"
          echo "NEW_IMAGE" > ./aws/dev/ecr/task_definitions/image.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./aws/dev/ecr/task_definitions/image.txt
          git commit -m "ci: Auto-update dev image to $NEW_IMAGE"
          # git push
